import React, {useRef} from 'react';
import {StyleSheet, Text, View} from 'react-native';
import QRCodeScanner from 'react-native-qrcode-scanner';
import {RNCamera} from 'react-native-camera';
import {useFocusEffect} from '@react-navigation/native';

const styles = StyleSheet.create({
  BottomContainer: {
    height: '100%',
    width: '100%',
    backgroundColor: '#2b3a66',
    justifyContent: 'center',
    alignItems: 'center',
  },
});

interface ScanProps {
  navigation: {
    navigate: (arg0: {
      name: string;
      params: {data: {data: string; isFromBookAppointment: boolean}};
    }) => void;
  };
}

export const Scan = (props: ScanProps) => {
  const qrCodeScannerRef = useRef<QRCodeScanner>(null);

  const onSuccess = e => {
    const data = e.data;
    const processedData = {data: '', isFromBookAppointment: false};
    try {
      processedData.data = JSON.parse(data);
      processedData.isFromBookAppointment = true;
    } catch (e) {
      processedData.data =
        typeof data === 'string' ? data : JSON.stringify(data);
      processedData.isFromBookAppointment = false;
    }
    props.navigation.navigate({
      name: 'ResultScreen',
      params: {data: processedData},
    });
  };

  useFocusEffect(
    React.useCallback(() => {
      qrCodeScannerRef.current && qrCodeScannerRef.current.reactivate();
    }, []),
  );

  return (
    <QRCodeScanner
      ref={qrCodeScannerRef}
      onRead={onSuccess}
      flashMode={RNCamera.Constants.FlashMode.off}
      topContent={
        <View
          style={{
            width: '100%',
            height: '100%',
            justifyContent: 'center',
            alignItems: 'center',
            backgroundColor: '#192954',
          }}>
          <Text style={{fontSize: 35, fontWeight: '600', color: '#FFFFFF'}}>
            Scan QR code
          </Text>
        </View>
      }
      bottomContent={
        <>
          <View style={styles.BottomContainer}>
            <Text
              style={{
                color: '#FFFFFF',
                textAlign: 'center',
                marginHorizontal: 20,
                fontWeight: '500',
              }}>
              This QR code scanner is specifically designed to scan QR code
              generated by Book Appointment app. Other QR codes' output cannot
              be guaranteed.
            </Text>
          </View>
        </>
      }
    />
  );
};
